[project]
name = "donutnodes"
description = "ComfyUI-DonutNodes offers advanced WIDEN merge algorithms, custom detailers, per-block SDXL control, dual-branch CLIP blending, and block-weighted LoRA stacking with enhanced memory management."
version = "1.0.15"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/DonutsDelivery/ComfyUI-DonutNodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "donutsdelivery"
DisplayName = "ComfyUI-DonutNodes"
Icon = ""
